/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * État de l'API et des artefacts
         * @description Vérifie que les artefacts sont chargés et renvoie leur date de construction.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPI du périmètre filtré
         * @description Effectifs (`n_rows` : base ; `n_portfolio_equiv` : estimation au taux supposé), churners
         *     attendus, revenu en jeu, répartition par niveau et campagne officielle (capacité 10 %,
         *     inactifs à part).
         */
        get: operations["kpis_api_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modalités de chaque filtre
         * @description Modalités de chaque dimension (ordre d'affichage) avec leur nombre de lignes, champs de
         *     tri de la liste des clients et bornes du curseur de capacité.
         */
        get: operations["filter_options_api_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histogramme des probabilités et répartition par niveau
         * @description Histogramme de la probabilité mensuelle corrigée (classes de 0,5 point, dernière classe
         *     ouverte à 15 %), empilé par niveau, quantiles et seuils des niveaux.
         */
        get: operations["risk_distribution_api_risk_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taux de churn croisé
         * @description Churn observé dans la base et risque attendu par cellule (x × y). Taux masqués (null)
         *     pour les cellules de moins de 30 lignes.
         */
        get: operations["heatmap_api_segments_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profils K-means : taille, risque, traits distinctifs
         * @description Un profil par segment comportemental (appris sans la cible) : effectifs, risque, revenu
         *     en jeu, action la plus fréquente et 3 traits (médianes comparées à la base entière).
         */
        get: operations["segment_profiles_api_segments_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{dimension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicateurs par modalité d'une dimension
         * @description Effectifs, taux de churn, revenu en jeu et part de High par modalité. Chaque modalité
         *     porte le filtre à ajouter pour un drill-down.
         */
        get: operations["segments_api_segments__dimension__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Importance des facteurs (SHAP)
         * @description Moyenne de |SHAP| sur les clients filtrés, facteurs actionnables et de contexte séparés,
         *     et parts par famille. SHAP explique le modèle, pas la causalité.
         */
        get: operations["drivers_api_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simuler une campagne de rétention
         * @description Clients ciblés (actifs, par risque décroissant), churners attendus contre hasard, revenu
         *     en jeu ; départs évités et revenu préservé selon le taux de succès **supposé** ; coût et
         *     solde seulement si `offer_cost` est fourni. Inclut la courbe de 1 à 50 % et les inactifs
         *     (non ciblés, traités à part).
         */
        get: operations["simulate_api_campaign_simulate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste paginée des clients
         * @description Pagination côté serveur. `total_n_rows` compte des clients de la base (lignes réelles).
         */
        get: operations["customers_api_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export CSV de la sélection filtrée
         * @description Toute la sélection (mêmes filtres, recherche et tri que la liste), sans pagination.
         */
        get: operations["customers_export_api_customers_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fiche client
         * @description Profil, probabilités, niveau, segment, 3 raisons actionnables, contexte et action.
         */
        get: operations["customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contributions SHAP (cascade)
         * @description De la valeur de base au log-odds du client : contributions les plus fortes, puis la
         *     somme des autres.
         */
        get: operations["customer_explanation_api_customers__customer_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poser une question à l'assistant (streaming SSE)
         * @description Réponse en **Server-Sent Events** (`text/event-stream`). Événements :
         *
         *     - `token` : `{"text": "...", "step": n}` — morceau de texte ;
         *     - `tool_call` : `{"name": "...", "args": {...}}` — outil appelé ;
         *     - `tool_result` : `{"name", "args", "duration_ms", "ok", "result"}` ;
         *     - `done` : réponse finale (schéma `ChatAnswer` : réponse, outils appelés, avertissements) ;
         *     - `error` : `{"message", "kind", "recoverable"}` ; si `recoverable`, la réponse continue en
         *       mode démonstration.
         *
         *     5 appels d'outils au plus par question ; seuls les 10 derniers messages d'historique sont
         *     transmis au modèle.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/explain-ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explication du risque pour un conseiller (IA)
         * @description 3 à 4 phrases à partir de la fiche et des contributions SHAP du client, « selon le
         *     modèle » ; nombres contrôlés par les garde-fous.
         */
        post: operations["explain_ai_api_customers__customer_id__explain_ai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/retention-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SMS et email de rétention (IA)
         * @description SMS (300 caractères au plus) et email adaptés au facteur dominant et à l'action, sans
         *     promesse chiffrée.
         */
        post: operations["retention_api_customers__customer_id__retention_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Résumé exécutif « Ce qu'il faut retenir »
         * @description 4 à 5 puces à partir des KPI et des statistiques par segment, mises en cache.
         */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fournisseur actif de l'assistant
         * @description Fournisseur (gemini ou demo), modèle et raison d'un éventuel mode démonstration. Ne fait
         *     aucun appel au fournisseur et n'expose jamais la clé.
         */
        get: operations["assistant_status_api_assistant_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisorExplanation */
        AdvisorExplanation: {
            /** Customer Id */
            customer_id: number;
            /**
             * Text
             * @description Explication en 3 à 4 phrases pour un conseiller.
             */
            text: string;
            /** Warnings */
            warnings: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** AssistantStatus */
        AssistantStatus: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "gemini" | "demo";
            /** Model */
            model: string;
            /** Available */
            available: boolean;
            /**
             * Live Llm
             * @description Vrai si un vrai modèle de langage répond.
             */
            live_llm: boolean;
            /**
             * Demo Reason
             * @description Pourquoi le mode démonstration est actif.
             */
            demo_reason: string | null;
            /**
             * Last Error
             * @description Dernière erreur du fournisseur (type).
             */
            last_error: string | null;
            /** Max Tool Calls */
            max_tool_calls: number;
            /** Max History Messages */
            max_history_messages: number;
        };
        /** Bands */
        Bands: {
            /** Tenure Band */
            tenure_band: string;
            /** Handset Age Band */
            handset_age_band: string;
            /** Usage Band */
            usage_band: string;
        };
        /** CampaignPoint */
        CampaignPoint: {
            /**
             * Capacity Pct
             * @description Part du périmètre contactée (%).
             */
            capacity_pct: number;
            /**
             * Targeted N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            targeted_n_rows: number;
            /**
             * Targeted N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            targeted_n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners: number;
            /**
             * Random Churners
             * @description Churners atteints par un ciblage au hasard.
             */
            random_churners: number;
            /** Lift Vs Random */
            lift_vs_random: number | null;
            /** Churners Per 1000 Contacted */
            churners_per_1000_contacted: number | null;
            /** Share Of Expected Churners */
            share_of_expected_churners: number | null;
            /**
             * Revenue At Risk Monthly
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk_monthly: number;
            /** Share Of Revenue At Risk */
            share_of_revenue_at_risk: number | null;
            /**
             * Observed Churners Check
             * @description Contrôle : churners historiques repondérés (doit être proche des churners attendus).
             */
            observed_churners_check: number;
            /**
             * Avoided Departures Hypothesis
             * @description HYPOTHÈSE : churners attendus × taux de succès saisi par l'utilisateur.
             */
            avoided_departures_hypothesis: number;
            /**
             * Preserved Revenue Monthly Hypothesis
             * @description HYPOTHÈSE : revenu en jeu × taux de succès ($ / mois).
             */
            preserved_revenue_monthly_hypothesis: number;
            /**
             * Preserved Revenue Horizon Hypothesis
             * @description HYPOTHÈSE : revenu mensuel préservé × horizon ($ sur l'horizon).
             */
            preserved_revenue_horizon_hypothesis: number;
            /**
             * Campaign Cost
             * @description Coût total, seulement si offer_cost fourni.
             */
            campaign_cost: number | null;
            /**
             * Net Balance
             * @description Revenu préservé sur l'horizon − coût ; seulement si offer_cost fourni.
             */
            net_balance: number | null;
        };
        /** CampaignSimulation */
        CampaignSimulation: {
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            user_hypotheses: components["schemas"]["UserHypotheses"];
            scope: components["schemas"]["Scope"];
            /** @description Résultat à la capacité demandée. */
            result: components["schemas"]["CampaignPoint"] | null;
            inactive: components["schemas"]["InactiveSummary"];
            /**
             * Curve
             * @description Courbe de 1 à 50 % de capacité.
             */
            curve: components["schemas"]["CampaignPoint"][];
        };
        /**
         * ChatAnswer
         * @description Contenu de l'événement SSE `done`.
         */
        ChatAnswer: {
            /** Answer */
            answer: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallRecord"][];
            /** Warnings */
            warnings: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Message
             * @description Question de l'utilisateur.
             * @example Quelle est la situation globale du portefeuille ?
             */
            message: string;
            /**
             * History
             * @description Historique (10 derniers messages conservés).
             */
            history?: components["schemas"]["ChatTurn"][];
        };
        /**
         * ChatTurn
         * @description Message d'historique (seuls les 10 derniers sont transmis au modèle).
         */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** CustomerDetail */
        CustomerDetail: {
            /** Customer Id */
            customer_id: number;
            /**
             * Partition
             * @enum {string}
             */
            partition: "train_oof" | "test";
            scores: components["schemas"]["CustomerScores"];
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "High" | "Medium" | "Low" | "Inactif";
            /** Inactive */
            inactive: boolean;
            segment: components["schemas"]["Segment"];
            bands: components["schemas"]["Bands"];
            /** Action */
            action: string;
            /** Dominant Family */
            dominant_family: string | null;
            /**
             * Reasons
             * @description Jusqu'à 3 facteurs actionnables qui augmentent le risque.
             */
            reasons: components["schemas"]["Factor"][];
            /**
             * Context
             * @description Facteurs non actionnables les plus influents.
             */
            context: components["schemas"]["Factor"][];
            /** Monthly Bill */
            monthly_bill: number | null;
            /** Revenue At Risk Monthly */
            revenue_at_risk_monthly: number;
            /** Profile */
            profile: components["schemas"]["ProfileField"][];
            /** Historical Churn Label */
            historical_churn_label: number;
            /** Historical Churn Note */
            historical_churn_note: string;
            /** Note */
            note: string;
        };
        /** CustomerExplanation */
        CustomerExplanation: {
            /** Customer Id */
            customer_id: number;
            /** Unit */
            unit: string;
            /** Base Value Log Odds */
            base_value_log_odds: number;
            /** Contributions */
            contributions: components["schemas"]["Factor"][];
            /** Others Contribution Log Odds */
            others_contribution_log_odds: number;
            /** Others Count */
            others_count: number;
            /** Log Odds */
            log_odds: number;
            /** P Raw From Log Odds */
            p_raw_from_log_odds: number;
            /** P Raw */
            p_raw: number;
            /** Note */
            note: string;
        };
        /** CustomerPage */
        CustomerPage: {
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            /** Search */
            search: string | null;
            /**
             * Sort
             * @enum {string}
             */
            sort: "p_real" | "revenue_at_risk_monthly" | "monthly_bill" | "tenure_months" | "handset_age_days" | "customer_id";
            /**
             * Order
             * @enum {string}
             */
            order: "asc" | "desc";
            /** Page */
            page: number;
            /** Size */
            size: number;
            /**
             * Total N Rows
             * @description Clients correspondants dans la base (Clients dans la base : lignes réelles du jeu de données (listes, filtres).)
             */
            total_n_rows: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["CustomerSummary"][];
        };
        /** CustomerScores */
        CustomerScores: {
            /**
             * P Raw
             * @description Probabilité du modèle brut (0-1).
             */
            p_raw: number;
            /**
             * P Calibrated
             * @description Probabilité calibrée sur la base (0-1).
             */
            p_calibrated: number;
            /**
             * P Real
             * @description Probabilité mensuelle au taux réel supposé (0-1).
             */
            p_real: number;
            /** P Real Note */
            p_real_note: string;
        };
        /** CustomerSummary */
        CustomerSummary: {
            /** Customer Id */
            customer_id: number;
            /**
             * Partition
             * @description train_oof : score hors fold ; test : modèle final.
             * @enum {string}
             */
            partition: "train_oof" | "test";
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "High" | "Medium" | "Low" | "Inactif";
            /**
             * P Real
             * @description Probabilité mensuelle de départ au taux supposé (0-1).
             */
            p_real: number;
            /**
             * P Calibrated
             * @description Probabilité calibrée sur la base (0-1, classement).
             */
            p_calibrated: number;
            /** Segment */
            segment: string;
            /** Action */
            action: string;
            /** Top Reason */
            top_reason: string | null;
            /**
             * Revenue At Risk Monthly
             * @description p_real × facture ($ / mois).
             */
            revenue_at_risk_monthly: number;
            /**
             * Monthly Bill
             * @description Facture mensuelle ($).
             */
            monthly_bill: number | null;
            /** Tenure Months */
            tenure_months: number | null;
            /** Handset Age Days */
            handset_age_days: number | null;
            /** Area */
            area: string;
            /** Inactive */
            inactive: boolean;
        };
        /** Driver */
        Driver: {
            /** Variable */
            variable: string;
            /** Label */
            label: string;
            /** Family */
            family: string;
            /** Family Label */
            family_label: string;
            /** Actionable */
            actionable: boolean;
            /**
             * Mean Abs Shap
             * @description Moyenne de |contribution SHAP| (log-odds).
             */
            mean_abs_shap: number;
            /**
             * Mean Shap
             * @description Moyenne signée (> 0 : pousse le risque vers le haut).
             */
            mean_shap: number;
            /**
             * Share Rows Increasing
             * @description Part des clients pour qui le facteur augmente le risque (0-1).
             */
            share_rows_increasing: number;
            /**
             * Share Pct
             * @description Part de l'importance totale (%).
             */
            share_pct: number;
            /**
             * Sensitive
             * @description Variable socio-démographique sensible : à ne pas afficher ni utiliser pour cibler.
             */
            sensitive: boolean;
        };
        /** DriverFamily */
        DriverFamily: {
            /** Family */
            family: string;
            /** Family Label */
            family_label: string;
            /** Actionable */
            actionable: boolean;
            /** Share Pct */
            share_pct: number;
        };
        /** Drivers */
        Drivers: {
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /** Unit */
            unit: string;
            /** Note */
            note: string;
            /** Actionable */
            actionable: components["schemas"]["Driver"][];
            /** Context */
            context: components["schemas"]["Driver"][];
            /** Families */
            families: components["schemas"]["DriverFamily"][];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Detail
             * @example Client 123 introuvable
             */
            detail: string;
        };
        /** ExecutiveSummary */
        ExecutiveSummary: {
            /** Title */
            title: string;
            /**
             * Bullets
             * @description 4 à 5 puces « Ce qu'il faut retenir ».
             */
            bullets: string[];
            /** Warnings */
            warnings: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Generated At */
            generated_at: string;
            /** Cached */
            cached: boolean;
        };
        /** Factor */
        Factor: {
            /** Variable */
            variable: string;
            /** Label */
            label: string;
            /**
             * Text
             * @description Phrase métier (situation du client).
             */
            text: string | null;
            /** Family */
            family: string;
            /** Family Label */
            family_label: string;
            /** Actionable */
            actionable: boolean;
            /** Contribution Log Odds */
            contribution_log_odds: number;
            /** Effect */
            effect: string;
        };
        /** FilterDimension */
        FilterDimension: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
            /** Label */
            label: string;
            /** Values */
            values: components["schemas"]["FilterValue"][];
        };
        /** FilterOptions */
        FilterOptions: {
            /** Dimensions */
            dimensions: components["schemas"]["FilterDimension"][];
            /** Customer Sort Fields */
            customer_sort_fields: ("p_real" | "revenue_at_risk_monthly" | "monthly_bill" | "tenure_months" | "handset_age_days" | "customer_id")[];
            /**
             * Capacity Pct Range
             * @description Bornes du curseur de capacité (%).
             */
            capacity_pct_range: number[];
        };
        /** FilterValue */
        FilterValue: {
            /** Value */
            value: string;
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * Artifacts Date
             * @description Date de construction des artefacts.
             */
            artifacts_date: string | null;
            /** Model */
            model: string | null;
            /** Calibration */
            calibration: string | null;
        };
        /** Heatmap */
        Heatmap: {
            /**
             * X
             * @enum {string}
             */
            x: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
            /**
             * Y
             * @enum {string}
             */
            y: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
            /** X Label */
            x_label: string;
            /** Y Label */
            y_label: string;
            /** X Values */
            x_values: string[];
            /** Y Values */
            y_values: string[];
            /** Min Rows For Rate */
            min_rows_for_rate: number;
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /** X */
            x: string;
            /** Y */
            y: string;
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number | null;
            /**
             * Observed Churn Rate In Base
             * @description null si trop peu de lignes.
             */
            observed_churn_rate_in_base: number | null;
            /**
             * Expected Churn Rate
             * @description null si trop peu de lignes.
             */
            expected_churn_rate: number | null;
            /**
             * Revenue At Risk
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk: number | null;
            /** Low Sample */
            low_sample: boolean;
        };
        /** HistogramBin */
        HistogramBin: {
            /**
             * P Real Min Pct
             * @description Borne basse de la classe (%).
             */
            p_real_min_pct: number;
            /**
             * P Real Max Pct
             * @description Borne haute (%) ; null = dernière classe.
             */
            p_real_max_pct: number | null;
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /** N Portfolio Equiv By Risk Level */
            n_portfolio_equiv_by_risk_level: {
                [key: string]: number;
            };
        };
        /**
         * Hypothesis
         * @description Hypothèses sous lesquelles les effectifs en équivalent portefeuille sont estimés.
         */
        Hypothesis: {
            /**
             * Real Churn Rate
             * @description Taux de churn mensuel réel SUPPOSÉ (hypothèse).
             * @example 0.02
             */
            real_churn_rate: number;
            /**
             * Real Churn Rate Is Hypothesis
             * @description Toujours vrai : non issu des données.
             */
            real_churn_rate_is_hypothesis: boolean;
            /**
             * Portfolio Size
             * @description Taille du portefeuille représenté par la base.
             * @example 100000
             */
            portfolio_size: number;
            /**
             * Note
             * @description Définition de n_portfolio_equiv, à afficher avec les KPI.
             */
            note: string;
        };
        /** InactiveSummary */
        InactiveSummary: {
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners: number;
            /**
             * Revenue At Risk Monthly
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk_monthly: number;
            /** Action */
            action: string;
            /** Note */
            note: string;
        };
        /**
         * Kpis
         * @description KPI du périmètre filtré.
         * @example {
         *       "expected_churners": 2002.2,
         *       "filters": {},
         *       "n_portfolio_equiv": 100000,
         *       "n_rows": 100000,
         *       "revenue_at_risk_monthly": 116162.4
         *     }
         */
        Kpis: {
            /**
             * Filters
             * @description Filtres appliqués.
             */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Rows Total
             * @description Clients dans la base, sans filtre.
             */
            n_rows_total: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /**
             * Share Of Portfolio
             * @description Part du portefeuille couverte par les filtres.
             */
            share_of_portfolio: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners: number;
            /**
             * Expected Churn Rate
             * @description Probabilité mensuelle moyenne (0-1).
             */
            expected_churn_rate: number | null;
            /**
             * Observed Churn Rate In Base
             * @description Churn historique dans la base (échantillon enrichi).
             */
            observed_churn_rate_in_base: number | null;
            /**
             * Revenue At Risk Monthly
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk_monthly: number;
            /**
             * Monthly Bill
             * @description Facture mensuelle totale, équivalent portefeuille.
             */
            monthly_bill: number;
            /** Revenue At Risk Share Of Bill */
            revenue_at_risk_share_of_bill: number | null;
            /**
             * Inactive N Rows
             * @description Clients inactifs dans la base (Clients dans la base : lignes réelles du jeu de données (listes, filtres).)
             */
            inactive_n_rows: number;
            /** By Risk Level */
            by_risk_level: components["schemas"]["LevelMetrics"][];
            official_campaign: components["schemas"]["OfficialCampaign"] | null;
            model: components["schemas"]["ModelInfo"];
        };
        /** LevelMetrics */
        LevelMetrics: {
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners?: number | null;
            /**
             * Revenue At Risk
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk?: number | null;
            /**
             * Monthly Bill
             * @description Facture mensuelle totale ($ / mois), équivalent portefeuille.
             */
            monthly_bill?: number | null;
            /**
             * Share Of Portfolio
             * @description Part du périmètre (0-1), en équivalent portefeuille.
             */
            share_of_portfolio?: number | null;
            /**
             * Observed Churn Rate In Base
             * @description Taux de churn historique observé dans la base (échantillon enrichi à ~50 % de churners : sert à comparer les groupes, pas à estimer un taux réel).
             */
            observed_churn_rate_in_base?: number | null;
            /**
             * Expected Churn Rate
             * @description Probabilité mensuelle moyenne de départ (0-1), portefeuille.
             */
            expected_churn_rate?: number | null;
            /**
             * Share High
             * @description Part de clients High (0-1), portefeuille.
             */
            share_high?: number | null;
            /**
             * Share Of Expected Churners
             * @description Part des churners attendus du périmètre.
             */
            share_of_expected_churners?: number | null;
            /**
             * Share Of Revenue At Risk
             * @description Part du revenu en jeu du périmètre.
             */
            share_of_revenue_at_risk?: number | null;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "High" | "Medium" | "Low" | "Inactif";
        };
        /** ModelInfo */
        ModelInfo: {
            /** Name */
            name: string | null;
            /** Calibration */
            calibration: string | null;
            /**
             * Auc Out Of Fold Train
             * @description AUC des scores hors fold du train.
             */
            auc_out_of_fold_train: number | null;
            /**
             * Auc Test
             * @description AUC sur le test (évaluation finale E9).
             */
            auc_test: number | null;
        };
        /**
         * OfficialCampaign
         * @description Campagne de référence : capacité de la config (10 %), clients actifs, inactifs à part.
         */
        OfficialCampaign: {
            /**
             * Capacity Pct
             * @description Part du périmètre contactée (%).
             * @example 10
             */
            capacity_pct: number;
            /**
             * Targeted N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            targeted_n_rows: number;
            /**
             * Targeted N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            targeted_n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners: number;
            /**
             * Churners Per 1000 Contacted
             * @description Futurs churners atteints pour 1 000 clients contactés (51 sur le portefeuille entier : chiffre de campagne officiel).
             * @example 51.1
             */
            churners_per_1000_contacted: number;
            /**
             * Random Churners Per 1000 Contacted
             * @description Au hasard (1 000 × taux supposé).
             * @example 20
             */
            random_churners_per_1000_contacted: number;
            /** Lift Vs Random */
            lift_vs_random: number;
            /**
             * Revenue At Risk Monthly
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk_monthly: number;
        };
        /** ProfileField */
        ProfileField: {
            /** Variable */
            variable: string;
            /** Label */
            label: string;
            /** Value */
            value: number | string | null;
            /** Unit */
            unit: string;
        };
        /** ProfileTrait */
        ProfileTrait: {
            /** Variable */
            variable: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /**
             * Segment Median
             * @description Médiane du segment (clients dans la base).
             */
            segment_median: number | null;
            /**
             * Overall Median
             * @description Médiane de toute la base.
             */
            overall_median: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher" | "lower";
            /**
             * Gap Iqr
             * @description Écart à la médiane globale, en écarts interquartiles.
             */
            gap_iqr: number | null;
        };
        /** RetentionMessage */
        RetentionMessage: {
            /** Customer Id */
            customer_id: number;
            /** Dominant Family */
            dominant_family: string | null;
            /** Action */
            action: string;
            /**
             * Sms
             * @description SMS de 300 caractères au plus.
             */
            sms: string;
            /** Sms Length */
            sms_length: number;
            /** Email Subject */
            email_subject: string;
            /** Email Body */
            email_body: string;
            /** Warnings */
            warnings: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
        };
        /** RiskDistribution */
        RiskDistribution: {
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            /** Unit */
            unit: string;
            /** Bins */
            bins: components["schemas"]["HistogramBin"][];
            /** Quantiles Portfolio Equiv Pct */
            quantiles_portfolio_equiv_pct: {
                [key: string]: number;
            };
            thresholds: components["schemas"]["Thresholds"];
            /** By Risk Level */
            by_risk_level: components["schemas"]["LevelMetrics"][];
        };
        /** Scope */
        Scope: {
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
        };
        /** Segment */
        Segment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** SegmentItem */
        SegmentItem: {
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners?: number | null;
            /**
             * Revenue At Risk
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk?: number | null;
            /**
             * Monthly Bill
             * @description Facture mensuelle totale ($ / mois), équivalent portefeuille.
             */
            monthly_bill?: number | null;
            /**
             * Share Of Portfolio
             * @description Part du périmètre (0-1), en équivalent portefeuille.
             */
            share_of_portfolio?: number | null;
            /**
             * Observed Churn Rate In Base
             * @description Taux de churn historique observé dans la base (échantillon enrichi à ~50 % de churners : sert à comparer les groupes, pas à estimer un taux réel).
             */
            observed_churn_rate_in_base?: number | null;
            /**
             * Expected Churn Rate
             * @description Probabilité mensuelle moyenne de départ (0-1), portefeuille.
             */
            expected_churn_rate?: number | null;
            /**
             * Share High
             * @description Part de clients High (0-1), portefeuille.
             */
            share_high?: number | null;
            /**
             * Share Of Expected Churners
             * @description Part des churners attendus du périmètre.
             */
            share_of_expected_churners?: number | null;
            /**
             * Share Of Revenue At Risk
             * @description Part du revenu en jeu du périmètre.
             */
            share_of_revenue_at_risk?: number | null;
            /**
             * Value
             * @description Modalité de la dimension.
             */
            value: string;
            /**
             * Filter
             * @description Filtre à ajouter pour un drill-down.
             */
            filter: {
                [key: string]: string[];
            };
        };
        /** SegmentProfile */
        SegmentProfile: {
            /**
             * N Rows
             * @description Clients dans la base : lignes réelles du jeu de données (listes, filtres).
             */
            n_rows: number;
            /**
             * N Portfolio Equiv
             * @description ESTIMATION : effectif équivalent dans un portefeuille réel de 100 000 clients au taux de churn supposé (hypothèse, 2 % par mois).
             */
            n_portfolio_equiv: number;
            /**
             * Expected Churners
             * @description Churners attendus sur un mois, en équivalent portefeuille (estimation).
             */
            expected_churners?: number | null;
            /**
             * Revenue At Risk
             * @description Revenu mensuel en jeu ($ / mois) = probabilité corrigée × facture, équivalent portefeuille.
             */
            revenue_at_risk?: number | null;
            /**
             * Monthly Bill
             * @description Facture mensuelle totale ($ / mois), équivalent portefeuille.
             */
            monthly_bill?: number | null;
            /**
             * Share Of Portfolio
             * @description Part du périmètre (0-1), en équivalent portefeuille.
             */
            share_of_portfolio?: number | null;
            /**
             * Observed Churn Rate In Base
             * @description Taux de churn historique observé dans la base (échantillon enrichi à ~50 % de churners : sert à comparer les groupes, pas à estimer un taux réel).
             */
            observed_churn_rate_in_base?: number | null;
            /**
             * Expected Churn Rate
             * @description Probabilité mensuelle moyenne de départ (0-1), portefeuille.
             */
            expected_churn_rate?: number | null;
            /**
             * Share High
             * @description Part de clients High (0-1), portefeuille.
             */
            share_high?: number | null;
            /**
             * Share Of Expected Churners
             * @description Part des churners attendus du périmètre.
             */
            share_of_expected_churners?: number | null;
            /**
             * Share Of Revenue At Risk
             * @description Part du revenu en jeu du périmètre.
             */
            share_of_revenue_at_risk?: number | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Filter
             * @description Filtre à ajouter pour un drill-down.
             */
            filter: {
                [key: string]: string[];
            };
            /**
             * Main Action
             * @description Action la plus fréquente parmi les High et Medium du segment.
             */
            main_action: string | null;
            /** Traits */
            traits: components["schemas"]["ProfileTrait"][];
        };
        /** SegmentProfiles */
        SegmentProfiles: {
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            /** Note */
            note?: string | null;
            /** Profiles */
            profiles: components["schemas"]["SegmentProfile"][];
        };
        /** Segments */
        Segments: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
            /** Label */
            label: string;
            /** Filters */
            filters: {
                [key: string]: string[];
            };
            hypothesis: components["schemas"]["Hypothesis"];
            /** Items */
            items: components["schemas"]["SegmentItem"][];
        };
        /** Thresholds */
        Thresholds: {
            /**
             * High P Calibrated
             * @description Seuil High sur la probabilité calibrée (0-1).
             */
            high_p_calibrated: number;
            /** Medium P Calibrated */
            medium_p_calibrated: number;
            /**
             * High P Real Pct
             * @description Même seuil, en probabilité mensuelle corrigée (%).
             */
            high_p_real_pct: number;
            /** Medium P Real Pct */
            medium_p_real_pct: number;
        };
        /** ToolCallRecord */
        ToolCallRecord: {
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms: number;
            /** Ok */
            ok: boolean;
        };
        /** UserHypotheses */
        UserHypotheses: {
            /** Success Rate */
            success_rate: number;
            /** Offer Cost Per Contact */
            offer_cost_per_contact: number | null;
            /** Revenue Horizon Months */
            revenue_horizon_months: number;
            /** Note */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    kpis_api_kpis_get: {
        parameters: {
            query?: {
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kpis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filter_options_api_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
        };
    };
    risk_distribution_api_risk_distribution_get: {
        parameters: {
            query?: {
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDistribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_segments_heatmap_get: {
        parameters: {
            query?: {
                /** @description Dimension en colonnes. */
                x?: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
                /** @description Dimension en lignes. */
                y?: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_profiles_api_segments_profiles_get: {
        parameters: {
            query?: {
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentProfiles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segments_api_segments__dimension__get: {
        parameters: {
            query?: {
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path: {
                dimension: "risk_level" | "cluster" | "area" | "tenure_band" | "handset_age_band" | "usage_band" | "action";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Segments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drivers_api_drivers_get: {
        parameters: {
            query?: {
                /** @description Facteurs par liste. */
                top?: number;
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drivers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_campaign_simulate_get: {
        parameters: {
            query?: {
                /** @description Part du périmètre contactée (%). */
                capacity_pct?: number;
                /** @description HYPOTHÈSE : part des churners ciblés retenus par l'offre (0-1). */
                success_rate?: number;
                /** @description Coût de l'offre par client contacté ($). Sans valeur : ni coût ni solde. */
                offer_cost?: number | null;
                /** @description HYPOTHÈSE : mois de revenu préservé comptés (revenu sur l'horizon et solde). */
                revenue_horizon_months?: number;
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSimulation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customers_api_customers_get: {
        parameters: {
            query?: {
                /** @description Champ de tri. */
                sort?: "p_real" | "revenue_at_risk_monthly" | "monthly_bill" | "tenure_months" | "handset_age_days" | "customer_id";
                /** @description asc ou desc. */
                order?: string;
                /** @description Page, à partir de 1. */
                page?: number;
                /** @description Clients par page. */
                size?: number;
                /** @description Fragment d'identifiant. */
                search?: string | null;
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customers_export_api_customers_export_get: {
        parameters: {
            query?: {
                /** @description Champ de tri. */
                sort?: "p_real" | "revenue_at_risk_monthly" | "monthly_bill" | "tenure_months" | "handset_age_days" | "customer_id";
                order?: string;
                search?: string | null;
                /** @description Niveau de risque. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                risk_level?: string[] | null;
                /** @description Segment K-means. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                cluster?: string[] | null;
                /** @description Région. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                area?: string[] | null;
                /** @description Tranche d'ancienneté. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                tenure_band?: string[] | null;
                /** @description Tranche d'âge du terminal. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                handset_age_band?: string[] | null;
                /** @description Tranche d'usage. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                usage_band?: string[] | null;
                /** @description Action suggérée. Valeurs possibles : GET /api/filters. Répéter le paramètre pour plusieurs valeurs (OU). */
                action?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV (séparateur « ; », virgule décimale, UTF-8 avec BOM) : une ligne par client de la base. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant client (Customer_ID). */
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Client introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer_explanation_api_customers__customer_id__explanation_get: {
        parameters: {
            query?: {
                top?: number;
            };
            header?: never;
            path: {
                /** @description Identifiant client (Customer_ID). */
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerExplanation"];
                };
            };
            /** @description Client introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Flux d'événements ; `done` suit le schéma ChatAnswer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatAnswer"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_ai_api_customers__customer_id__explain_ai_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant client (Customer_ID). */
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorExplanation"];
                };
            };
            /** @description Client introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retention_api_customers__customer_id__retention_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant client (Customer_ID). */
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionMessage"];
                };
            };
            /** @description Client introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutiveSummary"];
                };
            };
        };
    };
    assistant_status_api_assistant_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantStatus"];
                };
            };
        };
    };
}
